service: angular-ssr-serverless-deployment

plugins:
  - serverless-apigw-binary
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 192
  timeout: 10
  region: us-east-1
  stage: prod

package:
  exclude:
    - ./**
    - '!node_modules/@vendia/**'
  include:
    - "node_modules/aws-serverless-express/**"
    - "node_modules/binary-case/**"
    - "node_modules/type-is/**"
    - "node_modules/media-typer/**"
    - "node_modules/mime-types/**"
    - "node_modules/mime-db/**"
    - "node_modules/crypto-js/**"
    - "node_modules/jquery/**"
    - "dist/**"
    - "lambda.js"

custom:
  apigwBinary:
    types:
      - "*/*"

functions:
  api:
    handler: lambda.handler
    events:
      - http: GET /
      - http: "GET {proxy+}"
